name: Python Modpack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 升级至最新checkout版本

    - name: Set up Python
      uses: actions/setup-python@v5  # 升级至最新Python设置版本
      with:
        python-version: '3.12'      # 建议使用最新Python版本
        cache: 'pip'               # 添加依赖缓存
        cache-dependency-path: 'requirements.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run packaging
      run: |
        python pack.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 升级至v4版本
      with:
        name: modpack-build-${{ github.run_id }}  # 添加唯一ID防止覆盖
        path: |
          builds/*.zip
          builds/*.md5
          builds/*.sha1
        retention-days: 7  # 设置自动清理时间
        if-no-files-found: error  # 严格模式
