name: Python Modpack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run packaging
      run: |
        python pack.py

   
    - name: Set client zip path
      id: set-client
      run: |
        echo "::set-output name=client_zip::$(ls builds/Leisurely\ Life\ 1.20.1-*.zip)"
      shell: bash

    - name: Set server zip path
      id: set-server
      run: |
        echo "::set-output name=server_zip::$(ls builds/Leisurely\ Life\ Server\ 1.20.1-*.zip)"
      shell: bash

    - name: Set all zip path
      id: set-all
      run: |
        echo "::set-output name=all_zip::$(ls builds/*.zip)"
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: builds/
        retention-days: 7
        if-no-files-found: error