name: Python Modpack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run packaging
      run: |
        python pack.py

    - name: Setup compression environment
      run: |
        mkdir -p builds
        echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

    - name: Compress Client
      run: |
        cd build/client
        zip -qr "../../builds/Leisurely Life 1.20.1-${{ env.VERSION }}.zip" .

    - name: Compress Server
      run: |
        cd build/server
        zip -qr "../../builds/Leisurely Life Server 1.20.1-${{ env.VERSION }}.zip" .

    - name: Clean build directories
      run: |
        rm -rf build/client
        rm -rf build/server

    - name: Upload Client Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Leisurely-Life-Client-${{ github.run_id }}
        path: builds/Leisurely Life 1.20.1-*.zip
        retention-days: 7
        if-no-files-found: error

    - name: Upload Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Leisurely-Life-Server-${{ github.run_id }}
        path: builds/Leisurely Life Server 1.20.1-*.zip
        retention-days: 7
        if-no-files-found: error

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Leisurely-Life-All-${{ github.run_id }}
        path: builds/*.zip
        retention-days: 7
        if-no-files-found: error
