name: Python Modpack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run packaging
      run: |
        python pack.py

    # 获取客户端 ZIP 文件路径
    - name: Get client zip path
      id: client_zip
      run: |
        CLIENT_ZIP=$(ls builds/Leisurely\ Life\ 1.20.1-*.zip)
        echo "::set-output name=client_zip::$CLIENT_ZIP"

    # 获取服务端 ZIP 文件路径
    - name: Get server zip path
      id: server_zip
      run: |
        SERVER_ZIP=$(ls builds/Leisurely\ Life\ Server\ 1.20.1-*.zip)
        echo "::set-output name=server_zip::$SERVER_ZIP"

    # 上传客户端 ZIP（直接指定文件路径，避免二次压缩）
    - name: Upload Client Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Leisurely-Life-Client-${{ github.run_id }}
        path: ${{ steps.client_zip.outputs.client_zip }}
        retention-days: 7
        if-no-files-found: error

    # 上传服务端 ZIP（直接指定文件路径，避免二次压缩）
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Leisurely-Life-Server-${{ github.run_id }}
        path: ${{ steps.server_zip.outputs.server_zip }}
        retention-days: 7
        if-no-files-found: error