name: Python Modpack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run packaging
      run: |
        python pack.py

    # 获取客户端 ZIP 文件路径（使用环境文件）
    - name: Get client zip path
      run: |
        CLIENT_ZIP=$(ls builds/Leisurely\ Life\ 1.20.1-*.zip)
        echo "CLIENT_ZIP=$CLIENT_ZIP" >> $GITHUB_ENV

    # 获取服务端 ZIP 文件路径（使用环境文件）
    - name: Get server zip path
      run: |
        SERVER_ZIP=$(ls builds/Leisurely\ Life\ Server\ 1.20.1-*.zip)
        echo "SERVER_ZIP=$SERVER_ZIP" >> $GITHUB_ENV

    # 上传客户端 Artifact（直接指定环境变量路径）
    - name: Upload Client Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Leisurely-Life-Client-${{ github.run_id }}
        path: ${{ env.CLIENT_ZIP }}
        retention-days: 7
        if-no-files-found: error

    # 上传服务端 Artifact（直接指定环境变量路径）
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Leisurely-Life-Server-${{ github.run_id }}
        path: ${{ env.SERVER_ZIP }}
        retention-days: 7
        if-no-files-found: error

    # 上传所有 ZIP 文件（可选，保留原始行为）
    - name: Upload All Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Leisurely-Life-All-${{ github.run_id }}
        path: builds/*.zip
        retention-days: 7
        if-no-files-found: error
