name: Release Static Name Packages

on:
  push:
    tags:
      - 'v*'  # 匹配任意v开头的标签

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build packages
      run: python pack.py

    - name: Create Clean Artifacts
      run: |
        # 构建日期
        BUILD_DATE=$(date +'%Y.%m.%d')

        # 创建干净的构建目录
        mkdir -p release_artifacts
        
        # 打包客户端（固定名称）
        (cd build/client && zip -r ../../release_artifacts/Leisurely-Life-client.zip .)
        
        # 打包服务端（固定名称）
        (cd build/server && zip -r ../../release_artifacts/Leisurely-Life-server.zip .)

        # 生成日期
        echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV

        # 验证文件存在
        ls -lh release_artifacts/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: |
          ### 遗忘之海整合包 ${{ github.ref_name }}
          **构建日期**: ${{ env.BUILD_DATE }}

          包含以下整合包文件：
          - `Leisurely-Life-client.zip` (客户端)
          - `Leisurely-Life-server.zip` (服务端)
          
          版本标签：**${{ github.ref_name }}**
        files: |
          release_artifacts/Leisurely-Life-client.zip
          release_artifacts/Leisurely-Life-server.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
